# -*- coding: utf-8 -*-
"""NLU_Assgn_Q1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wts90OAtjD7sRslIvVjgzYhI1Jjldo4_
"""

!pip install pymupdf gensim wordcloud matplotlib scikit-learn

import fitz
import re
import os
from collections import Counter
from wordcloud import WordCloud
import matplotlib.pyplot as plt

def clean_pdf_text_v2(pdf_paths):
    raw_text = ""
    for path in pdf_paths:
        try:
            doc = fitz.open(path)
            for page in doc:
                raw_text += page.get_text()
        except Exception as e:
            print(f"Error loading {path}: {e}")
    text = raw_text.lower()
    text = text.replace("b.tech", "btech").replace("m.tech", "mtech").replace("ph.d", "phd")

    text = re.sub(r'[^a-z0-9\s]', ' ', text)

    # 4. Tokenize
    tokens = [word for word in text.split() if len(word) > 1]
    return tokens

pdf_files = ["Document1.pdf", "Document2.pdf","Document3.pdf","Document4.pdf","Document5.pdf","Document6.pdf","Document7.pdf","Document8.pdf","Document9.pdf","Document10.pdf","Document11.pdf","Document12.pdf","Document13.pdf","Document14.pdf","Document15.pdf"]

all_tokens = clean_pdf_text_v2(pdf_files)

# Verification Check
search_terms = ['btech', 'mtech', 'phd', 'ug', 'pg', 'iit']
print("Vocabulary Check:")
for term in search_terms:
    count = all_tokens.count(term)
    print(f"'{term}' appears {count} times")
all_tokens = clean_pdf_text_v2(pdf_files)

vocab = set(all_tokens)
print(f"Total Documents: {len(pdf_files)}")
print(f"Total Tokens: {len(all_tokens)}")
print(f"Vocabulary Size: {len(vocab)}")

# Word Cloud
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(" ".join(all_tokens))
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud)
plt.axis('off')
plt.show()

# Save cleaned corpus for deliverables
with open("corpus.txt", "w") as f:
    f.write(" ".join(all_tokens))

import torch
import torch.nn as nn
import torch.optim as optim

#Create Word-to-Index mappings
vocab = sorted(list(set(all_tokens)))
word_to_ix = {word: i for i, word in enumerate(vocab)}
ix_to_word = {i: word for i, word in enumerate(vocab)}
vocab_size = len(vocab)

#Create Training Pairs
def create_skipgram_data(tokens, window_size=2):
    data = []
    for i in range(window_size, len(tokens) - window_size):
        target = tokens[i]
        # Context words are those within the window
        contexts = [tokens[i-j] for j in range(1, window_size+1)] + \
                   [tokens[i+j] for j in range(1, window_size+1)]
        for context in contexts:
            data.append((word_to_ix[target], word_to_ix[context]))
    return data

training_data = create_skipgram_data(all_tokens)
print(f"Total training pairs: {len(training_data)}")

class Word2VecFromScratch(nn.Module):
    def __init__(self, vocab_size, embedding_dim):
        super(Word2VecFromScratch, self).__init__()
        # Layer 1: Input to Hidden---The Embeddings
        self.embeddings = nn.Embedding(vocab_size, embedding_dim)
        # Layer 2: Hidden to Output-->Predicting context
        self.linear = nn.Linear(embedding_dim, vocab_size)

    def forward(self, inputs):
        # inputs: [batch_size]
        embeds = self.embeddings(inputs)
        out = self.linear(embeds)
        return out

# Initialize
EMBEDDING_DIM = 100
scratch_model = Word2VecFromScratch(vocab_size, EMBEDDING_DIM)

def train_scratch_model(model, data, epochs=20):
    optimizer = optim.Adam(model.parameters(), lr=0.01)
    loss_function = nn.CrossEntropyLoss()

    for epoch in range(epochs):
        total_loss = 0

        for target_idx, context_idx in data[:1000]:
            target_tensor = torch.tensor([target_idx])
            context_tensor = torch.tensor([context_idx])

            model.zero_grad()
            log_probs = model(target_tensor)
            loss = loss_function(log_probs, context_tensor)

            loss.backward()
            optimizer.step()
            total_loss += loss.item()

        print(f"Epoch {epoch+1}, Loss: {total_loss/10000:.4f}")

train_scratch_model(scratch_model, training_data)

def get_similarity(word1, word2, model):
    if word1 not in word_to_ix or word2 not in word_to_ix:
        return 0.0

    weights = model.embeddings.weight.data
    v1 = weights[word_to_ix[word1]]
    v2 = weights[word_to_ix[word2]]

   #COSINE SIMILARITY
    similarity = torch.dot(v1, v2) / (torch.norm(v1) * torch.norm(v2))
    return similarity.item()
print(f"Similarity (research, phd): {get_similarity('research', 'phd', scratch_model):.4f}")

import torch

def get_nearest_neighbors(word, model, word_to_ix, ix_to_word, top_n=10):
    if word not in word_to_ix:
        return f"Word '{word}' not in vocabulary."
    weights = model.embeddings.weight.data

    target_idx = word_to_ix[word]
    target_vec = weights[target_idx].unsqueeze(0)
    cos_sim = torch.nn.functional.cosine_similarity(target_vec, weights)

    scores, indices = torch.topk(cos_sim, top_n + 1)

    neighbors = []
    for i in range(1, len(indices)):
        idx = indices[i].item()
        neighbors.append((ix_to_word[idx], scores[i].item()))

    return neighbors

def run_scratch_analogies(model, a, b, c, word_to_ix, ix_to_word):

    for w in [a, b, c]:
        if w not in word_to_ix:
            print(f"Skipping analogy: '{w}' missing from vocab.")
            return

    weights = model.embeddings.weight.data
    vec_a = weights[word_to_ix[a]]
    vec_b = weights[word_to_ix[b]]
    vec_c = weights[word_to_ix[c]]

    # The Analogy Vector
    target_vec = (vec_b - vec_a + vec_c).unsqueeze(0)

    # Find closest word to this new vector
    cos_sim = torch.nn.functional.cosine_similarity(target_vec, weights)
    score, index = torch.topk(cos_sim, 1)

    print(f"Analogy {a}:{b} :: {c}:? => Result: {ix_to_word[index.item()]} (Score: {score.item():.4f})")

# --- EXECUTION ---

print("NEAREST NEIGHBORS")
print("-" * 30)
target_words = ['research', 'student', 'phd', 'exam']

for word in target_words:
    nn = get_nearest_neighbors(word, scratch_model, word_to_ix, ix_to_word)
    print(f"\nTop 10 neighbors for '{word}':")
    if isinstance(nn, list):
        for name, score in nn:
            print(f"  - {name}: {score:.4f}")
    else:
        print(nn)

print("\n" + "-" * 30)
print("ANALOGY EXPERIMENTS")
# Example: ug : btech :: pg : mtech
run_scratch_analogies(scratch_model, 'ug', 'btech', 'pg', word_to_ix, ix_to_word)

word="jodhpur"
nn = get_nearest_neighbors(word, scratch_model, word_to_ix, ix_to_word)
print(f"\nTop 10 neighbors for '{word}':")
if isinstance(nn, list):
        for name, score in nn:
            print(f"  - {name}: {score:.4f}")
else:
        print(nn)

from sklearn.manifold import TSNE
import numpy as np
import matplotlib.pyplot as plt

def plot_embeddings_scratch(model, words, word_to_ix):

    embedding_dim = model.embeddings.weight.shape[1]
    arr = np.empty((0, embedding_dim), dtype='f')
    labels = []
    weights = model.embeddings.weight.data.cpu().numpy()

    for word in words:
        if word in word_to_ix:
            idx = word_to_ix[word]
            vector = weights[idx]
            arr = np.append(arr, [vector], axis=0)
            labels.append(word)
        else:
            print(f"Word '{word}' not found in vocabulary.")

    if len(labels) < 2:
        print("Error: Not enough words found to create a plot.")
        return

    perp = min(5, len(labels) - 1)
    tsne = TSNE(n_components=2, random_state=42, perplexity=perp, init='pca', learning_rate='auto')

    Y = tsne.fit_transform(arr)

    plt.figure(figsize=(10, 7))
    plt.scatter(Y[:, 0], Y[:, 1], color='red', edgecolors='black')

    for label, x, y in zip(labels, Y[:, 0], Y[:, 1]):
        plt.annotate(label, xy=(x, y), xytext=(5, 5), textcoords='offset points', fontsize=10)

    plt.title("t-SNE Visualization of IIT Jodhpur Word Clusters")
    plt.xlabel("Dimension 1")
    plt.ylabel("Dimension 2")
    plt.grid(True, linestyle='--', alpha=0.6)
    plt.show()

# Define sample words to check for clusters
sample_words = ['research', 'student', 'phd', 'exam', 'faculty', 'course', 'btech', 'mtech', 'iit', 'jodhpur']

plot_embeddings_scratch(scratch_model, sample_words, word_to_ix)